### ISSUE TITLE
ios 9 reloaddata problem

### ISSUE THREAD

**Issue by pmaccamp** [grillbiff/DragAndDropTableView#10]
Hi,

Thanks for the great library.  I recently came across an issue while testing ios9 in my app where reloadData no longer works after asynchronously fetching data from my server (my datasource methods are not called) - you can read more details here https://forums.developer.apple.com/message/41228#41228.

I don't think it has anything to do with DragAndDropTableView but I thought I would check if you'd tried it on ios9 and whether you had run into any issues.

Thanks!
-Patrick

**Comment by grillbiff** [comment]
Hi,

I haven't tested it with iOS9 yet but it's about time :D I'll let you know if I find anything.

Cheers
-erik

**Comment by mmatulski** [comment]
Hi, 
I just wanted to say that I also had  problem when using DragAndDropTableView in iOS9.
I have found that datasource and delegate do not get any requests.
I was setting them from XIB level so I have just tried to set them again from viewDidLoad method and it was enough for working again.

Regards,
Marek

BTW, thanks for your library, it is really awesome!

**Comment by grillbiff** [comment]
Hi, 

I finally had some time to look at it and it seems to me that both issues reported here has been solved in Xcode7 and iOS9 GM. I'll close this issue here but will reopen if your problems persist. 

Thanks for being patient :smile:
