### ISSUE TITLE
Crash app when drop.

### ISSUE THREAD

**Issue by Ying1986** [grillbiff/DragAndDropTableView#13]
Hello @grillbiff 
At my code, there are many changes insert/delete action to tableview while dragging (background processing).

I used [UITableView beginUpdate and endUpdate], and added NSLock lock] before beginUpdate, end unLock after endUpdate to prevent crash.

But your code call reloadData after release press,
So, my app crashes sometimes.
Can you avoid using reloadData?

After drop,I think, it is not needed to call reloadData , or if need,  it may be replaced by insert/deleteRows nested by begin/endUpdate.

I have added a crash callstack screenshot.

![screen shot 2015-11-23 at 8 49 13 pm](https://cloud.githubusercontent.com/assets/6648212/11346125/c7dc3822-9223-11e5-889a-ffa0f90e18a9.png)

Thank you.

**Comment by Ying1986** [comment]
Hello @grillbiff 

I have changed following code

```
#pragma clang diagnostic pop

        // remove image
        BOOL respondsToAnimateDraggedCells = [self.dataSource respondsToSelector:@selector(tableViewShouldAnimateDraggedCells:)];
        NSInteger sectionCount = [self numberOfSections];
        NSIndexSet* allIndexSet = [NSIndexSet indexSetWithIndexesInRange: NSMakeRange(0, sectionCount)];
        if(!respondsToAnimateDraggedCells ||
           (respondsToAnimateDraggedCells && [((NSObject<DragAndDropTableViewDataSource> *)self.dataSource) tableViewShouldAnimateDraggedCells:self]))
        {
            [UIView animateWithDuration:.3 animations:^{
                NSIndexPath *ipx = [self indexPathForCell:cell];
                if(ipx)
                    _cellSnapShotImageView.frame = [self rectForRowAtIndexPath:ipx];
            } completion:^(BOOL finished) {
                [_cellSnapShotImageView removeFromSuperview]; _cellSnapShotImageView = nil;

                [self beginUpdates];
                // reload
                [self reloadSections: allIndexSet withRowAnimation: UITableViewRowAnimationNone];
                [self endUpdates];
                if([self.delegate respondsToSelector:@selector(tableView:completeDraggingCellAtIndexPath:toIndexPath:)])
                {
                    [((NSObject<DragAndDropTableViewDelegate> *)self.delegate) tableView: self completeDraggingCellAtIndexPath: _originIndexPath toIndexPath: _movingIndexPath];
                }


            }];
        }
        else
        {
            [_cellSnapShotImageView removeFromSuperview]; _cellSnapShotImageView = nil;

            [self beginUpdates];
//            [self reloadData];
            [self reloadSections: allIndexSet withRowAnimation: UITableViewRowAnimationNone];
            [self endUpdates];

            if([self.delegate respondsToSelector:@selector(tableView:completeDraggingCellAtIndexPath:toIndexPath:)])
            {
                [((NSObject<DragAndDropTableViewDelegate> *)self.delegate) tableView: self completeDraggingCellAtIndexPath: _originIndexPath toIndexPath: _movingIndexPath];
            }
        }

```

DragAndDropTableView.h (added)

```
-(void)tableView:(DragAndDropTableView *)tableView completeDraggingCellAtIndexPath:(NSIndexPath *)sourceIndexPath toIndexPath:(NSIndexPath *)toIndexPath;
```

Please check and let me see your opinion about my code.

**Comment by grillbiff** [comment]
Hi,

it sounds reasonable that it should not reload the entire tableview each time a cell i moved. I won't have the time to go through your code right now but if you could make a pull request with the new code I will have a look at it as soon as possible

**Comment by Ying1986** [comment]
Hi,

I can't push my owner branch to your project.

But I think you should not reloadData at 333, 339.
Because, I have to change dataSource after finish draging complete,

If you call reloadData after call dragged... delegate, it should refresh while I modify tableview's dataSource.

I want is that tableview refresh or updated should be completed, before call drag-ended-delegate function.
So after call that delegate, DragAndDropTableView should not change or call to modify table or dataSource.

[DragAndDropTableView_h.txt](https://github.com/grillbiff/DragAndDropTableView/files/43650/DragAndDropTableView_h.txt)
[DragAndDropTableView_m.txt](https://github.com/grillbiff/DragAndDropTableView/files/43649/DragAndDropTableView_m.txt)

Please check it code, and optimize that code.
Perhaps, you don't mind in it.

And I think your library has some other issue that address incorrect row index after scroll while dragging.

Please help me.

Thank you.

**Comment by Ying1986** [comment]
Hello @grillbiff 

Did you check my code?

I want finish all refresh or modify process of tableview, before call finished delegate.

Let me see your opinion.

**Comment by grillbiff** [comment]
```
        if(!respondsToAnimateDraggedCells ||
           (respondsToAnimateDraggedCells && [((NSObject<DragAndDropTableViewDataSource> *)self.dataSource) tableViewShouldAnimateDraggedCells:self]))
        {
            [UIView animateWithDuration:.3 animations:^{
                NSIndexPath *ipx = [self indexPathForCell:cell];
                if(ipx)
                    _cellSnapShotImageView.frame = [self rectForRowAtIndexPath:ipx];
            } completion:^(BOOL finished) {
                [_cellSnapShotImageView removeFromSuperview]; _cellSnapShotImageView = nil;
                [self beginUpdates];
                [self reloadRowsAtIndexPaths:[self indexPathsForVisibleRows] withRowAnimation:UITableViewRowAnimationNone];
                [self endUpdates];
                if([self.delegate respondsToSelector:@selector(tableView:completedDraggingCellAtIndexPath:toIndexPath:)])
                {
                    [((NSObject<DragAndDropTableViewDelegate> *)self.delegate) tableView: self completedDraggingCellAtIndexPath: _originIndexPath toIndexPath: _movingIndexPath];
                }
            }];
        }
        else
        {
            [_cellSnapShotImageView removeFromSuperview]; _cellSnapShotImageView = nil;
            [self reloadData];
        }
```

I think it looks good. I couldn't remove the last reloadData without breaking the functionality but maybe this is not a requirement for you (only happens when you choose not to animate the cells into place)
pushed a branch 'remove-reload' where I have implemented your changes. Please test it with your code and get back to me

**Comment by Ying1986** [comment]
Dear @grillbiff 
Thank your reply

http://stackoverflow.com/questions/31144716/dynamically-changing-data-source-causing-deleterowsatindexpathsindexes-to-crash

Please search keyword 'reloadData crash' on google.

There are many crash examples.
reloadData is only useful on static DataSource, but as I said, my datasource is updating real-time.
So I want to remove "reloadData" any case.
and please insert "completedDraggingCellAtIndexPath" to determine drag-end state.

I ask to you again, please replace reloadData to the other function that end with endUpdated to complete tableview synchronous.
I want to complete sync-drag complete, not asyn.

At my code reloadRowsAtIndexPaths is not good, if you, it is possible to optimize by using insertRows or deleteRows, but I don't know about your code well.

Please check your code again and help me.

Regards.

**Comment by Ying1986** [comment]
@grillbiff 

I have check your code at branch 'remove-reloadData',
It's fine

but I want modify some little,

if (true)
{
it is ok
}
else
{
not good
}

else statement has some struct true part, except animation callbackfunction.

I want to complete sync any case, and call tableView:completedDraggingCellAtIndexPath:toIndexPath after there is nothing to process at your library.
So, after call tableView:completedDraggingCellAtIndexPath:toIndexPath, you should not request or change to tableview.

Thank you.

**Comment by grillbiff** [comment]
I updated the code to reload visible cells and call tableView:completedDraggingCellAtIndexPath:toIndexPath when not animating.

It could be done more efficiently than calling 
`[self reloadRowsAtIndexPaths:[self indexPathsForVisibleRows] withRowAnimation:UITableViewRowAnimationNone];`
but you would have to do some bookkeeping to keep track of and change the _originIndexPath and _movingIndexPath in the case that sections are deleted

**Comment by Ying1986** [comment]
Thank you,

I have found one issue,

```
        dispatch_async(dispatch_get_main_queue(), ^{
            reloadIndexPaths();
        });
```

Why did you call reloadIndexPaths as async?
and where is tableView:completedDraggingCellAtIndexPath:toIndexPath.

I need that delegate function because there is [NSLock unlock] in it.

**Comment by Ying1986** [comment]
@grillbiff 

Your code is good

how about change as following?

```
    if (...)
    {
        [UIView animateWithDuration:.3 animations:^{
            NSIndexPath *ipx = [self indexPathForCell:cell];
            if(ipx)
                _cellSnapShotImageView.frame = [self rectForRowAtIndexPath:ipx];
        } completion:^(BOOL finished) {
            [_cellSnapShotImageView removeFromSuperview]; _cellSnapShotImageView = nil;
            reloadIndexPaths();
        }];
    }
    else
    {
        [_cellSnapShotImageView removeFromSuperview]; _cellSnapShotImageView = nil;
        reloadIndexPaths();
    }
```

**Comment by grillbiff** [comment]
the call to the reload has to be done async (not sure why) for the table to be updated properly. 
Do you need the `tableView:completedDraggingCellAtIndexPath:toIndexPath:` to be called sync?

**Comment by Ying1986** [comment]
@grillbiff 
I don't mind in it tableView:completedDraggingCellAtIndexPath:toIndexPath is contained in reloadIndexPath.

reloadIndexPath is response only reload, and it dosen't extra mean complete.

How about following

void (^nofityComplete)() = ^{
{
            if([self.delegate respondsToSelector:@selector(tableView:completedDraggingCellAtIndexPath:toIndexPath:)])
            {
                [((NSObject<DragAndDropTableViewDelegate> *)self.delegate) tableView: self completedDraggingCellAtIndexPath: _originIndexPath toIndexPath: _movingIndexPath];
            }
}

and 
so finally

if (...)
{
...
    reloadIndexPaths()
        nofityComplete()
}
else
{
    reloadIndexPaths()
    nofityComplete()
}

**Comment by grillbiff** [comment]
not really sure what you are trying to accomplish. Do you want the `tableView:completedDraggingCellAtIndexPath:toIndexPath:` to always be called sync? If so you might as well use the `tableView:didEndDraggingCellAtIndexPath:toIndexPath:placeHolderView:`

**Comment by grillbiff** [comment]
If you like, I could make the `tableView:completedDraggingCellAtIndexPath:toIndexPath:` sync when the cell is not animating

**Comment by Ying1986** [comment]
tableView:didEndDraggingCellAtIndexPath:toIndexPath:placeHolderView: is good,

but is is called before refresh tableview.

```
    void (^nofityComplete)() = ^{
        {
              call  tableView:didEndDraggingCellAtIndexPath:toIndexPath:placeHolderView:
        }

        and
        so finally

        if (...)
        {
            ...
            reloadIndexPaths()
            nofityComplete()
        }
        else
        {
            reloadIndexPaths()
            nofityComplete()
        }
```

**Comment by grillbiff** [comment]
alright, but reloading the indexPaths synchronously is not working, uncertain why but if you want you can look into it

**Comment by Ying1986** [comment]
endUpdate is sync function for drawing, even though refresh has animation

begin...
    refresh1
endUpdate

begin
     refresh 2
endUpdage

Do you think refresh2 is conflict with refresh 1?
No, endUpdate is sync for drawing. Don't worry about it.

**Comment by Ying1986** [comment]
In this issue, it is very important to use endUpdate instead reloadData.

ex

[self reloadData]

dataSource change
[self reloadData]

do you think this code run correctly?
Perhaps it will be crashed.

**Comment by Ying1986** [comment]
but it is possible to prevent crash when use endUpdate

**Comment by Ying1986** [comment]
I have added you to my Skype account.

**Comment by Ying1986** [comment]
@grillbiff 
Hello, can you talk on Skype?

**Comment by Ying1986** [comment]
@grillbiff 

I have fixed that issue. Please check it and inform asap
[DragAndDropTableView_m.txt](https://github.com/grillbiff/DragAndDropTableView/files/45518/DragAndDropTableView_m.txt)

**Comment by grillbiff** [comment]
If you are in a hurry just use your own fork and I will check it when I have time. Instead of sending me code in text files you can make a pull request.

https://help.github.com/articles/using-pull-requests/

**Comment by Ying1986** [comment]
@grillbiff 

How can I create pull request?

![pull-reqeust](https://cloud.githubusercontent.com/assets/6648212/11437438/5fab5762-94f6-11e5-9b7c-e16bb652599b.png)

**Comment by grillbiff** [comment]
did you make a proper fork of the project? that looks more like a branch

**Comment by Ying1986** [comment]
Can I create pull request without my branch?

**Comment by Ying1986** [comment]
@grillbiff 

Hello

It is very difficult to work with you.
I'll remove your pod from my project and add modified files.
Good luck your time.
