### ISSUE TITLE
Crash when adding a cell to an empty table

### ISSUE THREAD

**Issue by boazin** [grillbiff/DragAndDropTableView#8]
Not sure if what I wrote in the headline is the cause but this is the symptom.

When the UItableView is empty, and I `insertRowsAtIndexPaths` I get the following crash:
```
*** Assertion failure in -[DragAndDropTableView _endCellAnimationsWithContext:], /SourceCache/UIKit_Sim/UIKit-3347.44/UITableView.m:1623
```

I switched back to regular UITableView (to see if DragAndDrop is the problem) - it works :( so it's definitely something with DragAndDrop...

The code:
```
    ChapterDataItem *item = [[ChapterDataItem alloc] init];
    item.type = @"text";
        dispatch_async(dispatch_get_main_queue(), ^{
            [chaptersArray addObject:item]; //add object should be on the same thread for consistency of the data
            NSIndexPath *newIndexPath = [NSIndexPath indexPathForRow:[chaptersArray count]-1 inSection:0];
            [self.tableView insertRowsAtIndexPaths:[NSArray arrayWithObject:newIndexPath] withRowAnimation:UITableViewRowAnimationFade];
        });
```

The number of rows returns the correct number of cells (nothing fishy here)
```
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    if (section == 0)
    {
        return [chaptersArray count];
    }
}
```

Any help will be appreciated...

**Comment by grillbiff** [comment]
you should wrap your inserts in beginUpdates and endUpdates 
```
[self.tableView beginUpdates];

[chaptersArray addObject:item];
NSIndexPath *newIndexPath = [NSIndexPath indexPathForRow:[chaptersArray count]-1 inSection:0];
[self.tableView insertRowsAtIndexPaths:[NSArray arrayWithObject:newIndexPath] withRowAnimation:UITableViewRowAnimationFade];

[self.tableView endUpdates];
```

Not sure if that is the solution to your particular problem so if it's still crashing let me know

**Comment by boazin** [comment]
unfortunately it still crashes. I can verify that it happens on `endupdates`

Crash is:

**** Assertion failure in -[DragAndDropTableView
_endCellAnimationsWithContext:],
/SourceCache/UIKit_Sim/UIKit-3347.44/UITableView.m:1623*

**Comment by grillbiff** [comment]
ok, tested it myself and I have verified that it is a bug. I'll try to fix it as soon as possible

**Comment by boazin** [comment]
Hey @grillbiff - If you have any direction on where you think the bug is and you can direct me to it so I can investigate and assist, I'll be happy to...

**Comment by grillbiff** [comment]
Hi, I uploaded a hotfix which you can try out 
hotfix/issue-#8

Basically none of insertRow, deleteRow or moveRow was working properly with empty sections. I haven't got around to fix the moveRow function yet either so let me know if this is something you need right away.

**Comment by boazin** [comment]
Well - now deleteRow is crashing (need to delete one before I can verify an insert is working)

The code:
```
[chaptersArray removeObjectAtIndex:indexPath.row];
            [self.tableView deleteRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationFade];
```
(chaptersArray count after remove is 0)

Causes:
```
/SourceCache/UIKit_Sim/UIKit-3347.44/UITableView.m:1623
2015-06-20 18:49:09.562 Cookila copy[13792:345918] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (1) must be equal to the number of rows contained in that section before the update (1), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'
```

**Comment by boazin** [comment]
OK. After diving into your code and wrapping it with `beginUpdates` `endUpdates` it works. I'd love a more elegant solution, but that will certainly do...
Regarding the MoveRows - I have only 1 section - and when there are 0 or 1 cells - the drag is disabled - so no rush there...

I'll do some more testing and report bugs if I spot them

Thanks for the help!

**Comment by grillbiff** [comment]
ok, if you made any changes to DragAndDropTableView would you mind sending me a pull request so I can have a look at it?

**Comment by boazin** [comment]
I was misunderstood. I wrapped the original call with `beginUpdates` and `endUpdates`. No changes were made in your code.
I was wondering if there is a way to not "force" the user to do it (it is un-orthodox to call `beginUpdates` and `endUpdates` for a single action)

**Comment by grillbiff** [comment]
aha I see :)

my understanding is that you should wrap all changes in begin/endUpdates if you want them animated, otherwise you have to use one of the reload functions
